defaults:
  - experiments: exp_1
  - _self_
mode: controllable
domain: zelda
process: train
slurm: true

training_dataset_sizes:
  - 100000
  - 500000
  - 400000
  - 900000
  - 1000000
  - 700000
  - 800000
  - 600000
  - 300000
  - 200000
obs_sizes:
  - 21
  - 5
  - 1
  - 7
  - 11
  - 17
  - 15
  - 3
  - 9
  - 19
  - 13
trajectory_lengths:
  - 77
  - 1
  - 61
  - 15
  - 38
  - 53
  - 46
  - 69
  - 7
  - 23
  - 30